dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0_beta.gemfile
before_install:
  # Travis' Ruby 2.5.0 ships broken rubygems, won't run rake.
  # Workaround: update rubygems. See travis-ci issue 8978
  - gem update --system
notifications:
  email: false
