version: 2

jobs:
  "rails-5-2": &job
    parallelism: 1
    docker: &job_docker
      - &job_docker_ruby
        image: circleci/ruby:2.6
        environment: &job_docker_ruby_env
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          BUNDLE_GEMFILE: gemfiles/rails_5_2.gemfile
    steps:
      - checkout

      - run:
          # Remove the non-appraisal gemfile for safety: we never want to use it.
          name: Prepare bundler
          command: bundle -v && rm Gemfile

      - run:
          name: Compute a gemfile lock
          command: bundle lock && cp "${BUNDLE_GEMFILE}.lock" /tmp/gem-lock

      - restore_cache:
          keys:
            - iknow_cache-{{ checksum "/tmp/gem-lock" }}
            - iknow_cache-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: iknow_cache-{{ checksum "/tmp/gem-lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run minitest
          command: bundle exec rake test

      - store_test_results:
          path: test/reports

  "rails-6-0-beta":
    <<: *job
    docker:
      - <<: *job_docker_ruby
        environment:
          <<: *job_docker_ruby_env
          BUNDLE_GEMFILE: gemfiles/rails_6_0_beta.gemfile

workflows:
  version: 2
  build:
    jobs:
      - "rails-5-2"
      - "rails-6-0-beta"
