version: 2.1

executors:
  ruby:
    parameters:
      ruby-version:
        type: string
        default: "2.7"
      gemfile:
        type: string
        default: "Gemfile"
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          BUNDLE_GEMFILE: << parameters.gemfile >>

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      gemfile:
        type: string
    executor:
      name: ruby
      ruby-version: << parameters.ruby-version >>
      gemfile: << parameters.gemfile >>
    parallelism: 1
    steps:
      - checkout

      - run:
          # Remove the non-appraisal gemfile for safety: we never want to use it.
          name: Prepare bundler
          command: bundle -v && rm Gemfile

      - run:
          name: Compute a gemfile lock
          command: bundle lock && cp "${BUNDLE_GEMFILE}.lock" /tmp/gem-lock

      - restore_cache:
          keys:
            - iknow_cache-<< parameters.ruby-version >>-{{ checksum "/tmp/gem-lock" }}
            - iknow_cache-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: iknow_cache-<< parameters.ruby-version >>-{{ checksum "/tmp/gem-lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run minitest
          command: bundle exec rake test

      - store_test_results:
          path: test/reports

  publish:
    executor: ruby
    steps:
       - checkout
       - run:
           name: Setup Rubygems
           command: |
             mkdir ~/.gem &&
             echo -e "---\r\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials &&
             chmod 0600 ~/.gem/credentials
       - run:
           name: Publish to Rubygems
           command: |
             gem build iknow_cache.gemspec
             gem push iknow_cache-*.gem

workflows:
  version: 2.1
  build:
    jobs:
      - test:
          name: 'ruby 2.7 rails 5.2'
          ruby-version: "2.7"
          gemfile: gemfiles/rails_5_2.gemfile
      - test:
          name: 'ruby 3.0 rails 6.1'
          ruby-version: "3.0"
          gemfile: gemfiles/rails_6_1.gemfile
      - test:
          name: 'ruby 3.0 rails 7.0'
          ruby-version: "3.0"
          gemfile: gemfiles/rails_7_0.gemfile
      - publish:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
